package com.web.server.ibatis.daoImpl;

import com.web.server.ibatis.dao.ConsommablematerielDAO;
import com.web.server.ibatis.model.Consommablemateriel;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ConsommablematerielDAOImpl extends SqlMapClientDaoSupport implements ConsommablematerielDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table consommablemateriel
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public ConsommablematerielDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table consommablemateriel
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int deleteByPrimaryKey(Integer idConsommable) {
        Consommablemateriel key = new Consommablemateriel();
        key.setIdConsommable(idConsommable);
        int rows = getSqlMapClientTemplate().delete("consommablemateriel.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table consommablemateriel
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insert(Consommablemateriel record) {
        getSqlMapClientTemplate().insert("consommablemateriel.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table consommablemateriel
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insertSelective(Consommablemateriel record) {
        getSqlMapClientTemplate().insert("consommablemateriel.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table consommablemateriel
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Consommablemateriel selectByPrimaryKey(Integer idConsommable) {
        Consommablemateriel key = new Consommablemateriel();
        key.setIdConsommable(idConsommable);
        Consommablemateriel record = (Consommablemateriel) getSqlMapClientTemplate().queryForObject("consommablemateriel.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table consommablemateriel
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKeySelective(Consommablemateriel record) {
        int rows = getSqlMapClientTemplate().update("consommablemateriel.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table consommablemateriel
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKey(Consommablemateriel record) {
        int rows = getSqlMapClientTemplate().update("consommablemateriel.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}