package com.web.server.ibatis.daoImpl;

import java.util.List;

import com.web.server.ibatis.dao.DemandeDAO;
import com.web.server.ibatis.model.Demande;


import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DemandeDAOImpl extends SqlMapClientDaoSupport implements DemandeDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table demande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public DemandeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table demande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public int deleteByPrimaryKey(Integer iddemande) {
		Demande key = new Demande();
		key.setIddemande(iddemande);
		int rows = getSqlMapClientTemplate().delete(
				"demande.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table demande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void insert(Demande record) {
		getSqlMapClientTemplate().insert("demande.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table demande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void insertSelective(Demande record) {
		getSqlMapClientTemplate().insert(
				"demande.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table demande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public Demande selectByPrimaryKey(Integer iddemande) {
		Demande key = new Demande();
		key.setIddemande(iddemande);
		Demande record = (Demande) getSqlMapClientTemplate().queryForObject(
				"demande.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table demande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public int updateByPrimaryKeySelective(Demande record) {
		int rows = getSqlMapClientTemplate().update(
				"demande.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table demande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public int updateByPrimaryKey(Demande record) {
		int rows = getSqlMapClientTemplate().update(
				"demande.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	@SuppressWarnings("unchecked")
 	public List<Demande>getAll(){
 	    	
 	    	return (List<Demande>) getSqlMapClientTemplate().queryForList("demande.getAll");
 	    }
	
	
	@SuppressWarnings("unchecked")
	public List<Demande>getByIdEtudiant(int Id ){
		Demande r=new Demande();
		   r.setIdetudiant(Id);
		  
		   
		   
	    	
	    	return (List<Demande>) getSqlMapClientTemplate().queryForList("demande.getByIdEtudiant",r);
	    }
}