package com.web.server.ibatis.daoImpl;

import com.web.server.ibatis.dao.DeplacementhibergmentDAO;
import com.web.server.ibatis.model.Deplacementhibergment;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DeplacementhibergmentDAOImpl extends SqlMapClientDaoSupport implements DeplacementhibergmentDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public DeplacementhibergmentDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int deleteByPrimaryKey(Integer iddeplacementhibergement) {
        Deplacementhibergment key = new Deplacementhibergment();
        key.setIddeplacementhibergement(iddeplacementhibergement);
        int rows = getSqlMapClientTemplate().delete("deplacementhibergment.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insert(Deplacementhibergment record) {
        getSqlMapClientTemplate().insert("deplacementhibergment.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insertSelective(Deplacementhibergment record) {
        getSqlMapClientTemplate().insert("deplacementhibergment.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Deplacementhibergment selectByPrimaryKey(Integer iddeplacementhibergement) {
        Deplacementhibergment key = new Deplacementhibergment();
        key.setIddeplacementhibergement(iddeplacementhibergement);
        Deplacementhibergment record = (Deplacementhibergment) getSqlMapClientTemplate().queryForObject("deplacementhibergment.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKeySelective(Deplacementhibergment record) {
        int rows = getSqlMapClientTemplate().update("deplacementhibergment.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKey(Deplacementhibergment record) {
        int rows = getSqlMapClientTemplate().update("deplacementhibergment.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}