package com.web.server.ibatis.daoImpl;

import com.web.server.ibatis.dao.DocumentationDAO;
import com.web.server.ibatis.model.Documentation;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DocumentationDAOImpl extends SqlMapClientDaoSupport implements DocumentationDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table documentation
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public DocumentationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table documentation
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int deleteByPrimaryKey(Integer iddocumentation) {
        Documentation key = new Documentation();
        key.setIddocumentation(iddocumentation);
        int rows = getSqlMapClientTemplate().delete("documentation.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table documentation
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insert(Documentation record) {
        getSqlMapClientTemplate().insert("documentation.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table documentation
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insertSelective(Documentation record) {
        getSqlMapClientTemplate().insert("documentation.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table documentation
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Documentation selectByPrimaryKey(Integer iddocumentation) {
        Documentation key = new Documentation();
        key.setIddocumentation(iddocumentation);
        Documentation record = (Documentation) getSqlMapClientTemplate().queryForObject("documentation.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table documentation
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKeySelective(Documentation record) {
        int rows = getSqlMapClientTemplate().update("documentation.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table documentation
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKey(Documentation record) {
        int rows = getSqlMapClientTemplate().update("documentation.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}