package com.web.server.ibatis.daoImpl;

import com.web.server.ibatis.dao.EquipementDAO;
import com.web.server.ibatis.model.Equipement;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EquipementDAOImpl extends SqlMapClientDaoSupport implements EquipementDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public EquipementDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int deleteByPrimaryKey(Integer idEquipement) {
        Equipement key = new Equipement();
        key.setIdEquipement(idEquipement);
        int rows = getSqlMapClientTemplate().delete("equipement.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insert(Equipement record) {
        getSqlMapClientTemplate().insert("equipement.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insertSelective(Equipement record) {
        getSqlMapClientTemplate().insert("equipement.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Equipement selectByPrimaryKey(Integer idEquipement) {
        Equipement key = new Equipement();
        key.setIdEquipement(idEquipement);
        Equipement record = (Equipement) getSqlMapClientTemplate().queryForObject("equipement.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKeySelective(Equipement record) {
        int rows = getSqlMapClientTemplate().update("equipement.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKey(Equipement record) {
        int rows = getSqlMapClientTemplate().update("equipement.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}