package com.web.server.ibatis.daoImpl;

import com.web.server.ibatis.dao.EtudiantDAO;
import com.web.server.ibatis.model.Etudiant;


import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EtudiantDAOImpl extends SqlMapClientDaoSupport implements EtudiantDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public EtudiantDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int deleteByPrimaryKey(Integer idEtudiant) {
        Etudiant key = new Etudiant();
        key.setIdEtudiant(idEtudiant);
        int rows = getSqlMapClientTemplate().delete("etudiant.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insert(Etudiant record) {
        getSqlMapClientTemplate().insert("etudiant.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insertSelective(Etudiant record) {
        getSqlMapClientTemplate().insert("etudiant.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Etudiant selectByPrimaryKey(Integer idEtudiant) {
        Etudiant key = new Etudiant();
        key.setIdEtudiant(idEtudiant);
        Etudiant record = (Etudiant) getSqlMapClientTemplate().queryForObject("etudiant.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKeySelective(Etudiant record) {
        int rows = getSqlMapClientTemplate().update("etudiant.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKey(Etudiant record) {
        int rows = getSqlMapClientTemplate().update("etudiant.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    
    
    
	public Etudiant isExiste(String login,String pwd){
		Etudiant rv =new Etudiant();
			rv.setLogin(login);
			rv.setPassword(pwd);
			
			return (Etudiant)getSqlMapClientTemplate().queryForObject("etudiant.isExiste",rv);
			
		}
}