package com.web.server.ibatis.daoImpl;

import com.web.server.ibatis.dao.MaintenancediveresDAO;
import com.web.server.ibatis.model.Maintenancediveres;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MaintenancediveresDAOImpl extends SqlMapClientDaoSupport implements MaintenancediveresDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public MaintenancediveresDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int deleteByPrimaryKey(Integer idmainetencedivers) {
        Maintenancediveres key = new Maintenancediveres();
        key.setIdmainetencedivers(idmainetencedivers);
        int rows = getSqlMapClientTemplate().delete("maintenancediveres.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insert(Maintenancediveres record) {
        getSqlMapClientTemplate().insert("maintenancediveres.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insertSelective(Maintenancediveres record) {
        getSqlMapClientTemplate().insert("maintenancediveres.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Maintenancediveres selectByPrimaryKey(Integer idmainetencedivers) {
        Maintenancediveres key = new Maintenancediveres();
        key.setIdmainetencedivers(idmainetencedivers);
        Maintenancediveres record = (Maintenancediveres) getSqlMapClientTemplate().queryForObject("maintenancediveres.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKeySelective(Maintenancediveres record) {
        int rows = getSqlMapClientTemplate().update("maintenancediveres.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKey(Maintenancediveres record) {
        int rows = getSqlMapClientTemplate().update("maintenancediveres.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}