package com.web.server.ibatis.daoImpl;

import com.web.server.ibatis.dao.MissionsDAO;
import com.web.server.ibatis.model.Missions;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MissionsDAOImpl extends SqlMapClientDaoSupport implements MissionsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public MissionsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int deleteByPrimaryKey(Integer idmissions) {
        Missions key = new Missions();
        key.setIdmissions(idmissions);
        int rows = getSqlMapClientTemplate().delete("missions.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insert(Missions record) {
        getSqlMapClientTemplate().insert("missions.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insertSelective(Missions record) {
        getSqlMapClientTemplate().insert("missions.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Missions selectByPrimaryKey(Integer idmissions) {
        Missions key = new Missions();
        key.setIdmissions(idmissions);
        Missions record = (Missions) getSqlMapClientTemplate().queryForObject("missions.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKeySelective(Missions record) {
        int rows = getSqlMapClientTemplate().update("missions.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKey(Missions record) {
        int rows = getSqlMapClientTemplate().update("missions.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}