package com.web.server.ibatis.daoImpl;

import com.web.server.ibatis.dao.RenumerationDAO;
import com.web.server.ibatis.model.Renumeration;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RenumerationDAOImpl extends SqlMapClientDaoSupport implements RenumerationDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public RenumerationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int deleteByPrimaryKey(Integer idrenumaration) {
        Renumeration key = new Renumeration();
        key.setIdrenumaration(idrenumaration);
        int rows = getSqlMapClientTemplate().delete("renumeration.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insert(Renumeration record) {
        getSqlMapClientTemplate().insert("renumeration.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insertSelective(Renumeration record) {
        getSqlMapClientTemplate().insert("renumeration.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Renumeration selectByPrimaryKey(Integer idrenumaration) {
        Renumeration key = new Renumeration();
        key.setIdrenumaration(idrenumaration);
        Renumeration record = (Renumeration) getSqlMapClientTemplate().queryForObject("renumeration.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKeySelective(Renumeration record) {
        int rows = getSqlMapClientTemplate().update("renumeration.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKey(Renumeration record) {
        int rows = getSqlMapClientTemplate().update("renumeration.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}