package com.web.server.ibatis.daoImpl;

import com.web.server.ibatis.dao.SoustraitanceDAO;
import com.web.server.ibatis.model.Soustraitance;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SoustraitanceDAOImpl extends SqlMapClientDaoSupport implements SoustraitanceDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public SoustraitanceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int deleteByPrimaryKey(Integer idTraitence) {
        Soustraitance key = new Soustraitance();
        key.setIdTraitence(idTraitence);
        int rows = getSqlMapClientTemplate().delete("soustraitance.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insert(Soustraitance record) {
        getSqlMapClientTemplate().insert("soustraitance.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insertSelective(Soustraitance record) {
        getSqlMapClientTemplate().insert("soustraitance.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Soustraitance selectByPrimaryKey(Integer idTraitence) {
        Soustraitance key = new Soustraitance();
        key.setIdTraitence(idTraitence);
        Soustraitance record = (Soustraitance) getSqlMapClientTemplate().queryForObject("soustraitance.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKeySelective(Soustraitance record) {
        int rows = getSqlMapClientTemplate().update("soustraitance.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKey(Soustraitance record) {
        int rows = getSqlMapClientTemplate().update("soustraitance.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}