package com.web.server.ibatis.daoImpl;

import com.web.server.ibatis.dao.StageDAO;
import com.web.server.ibatis.model.Stage;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class StageDAOImpl extends SqlMapClientDaoSupport implements StageDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public StageDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int deleteByPrimaryKey(Integer idStage) {
        Stage key = new Stage();
        key.setIdStage(idStage);
        int rows = getSqlMapClientTemplate().delete("stage.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insert(Stage record) {
        getSqlMapClientTemplate().insert("stage.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void insertSelective(Stage record) {
        getSqlMapClientTemplate().insert("stage.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Stage selectByPrimaryKey(Integer idStage) {
        Stage key = new Stage();
        key.setIdStage(idStage);
        Stage record = (Stage) getSqlMapClientTemplate().queryForObject("stage.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKeySelective(Stage record) {
        int rows = getSqlMapClientTemplate().update("stage.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public int updateByPrimaryKey(Stage record) {
        int rows = getSqlMapClientTemplate().update("stage.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}