package com.web.server.ibatis.dao;

import com.web.server.ibatis.model.Deplacementhibergment;

public interface DeplacementhibergmentDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int deleteByPrimaryKey(Integer iddeplacementhibergement);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insert(Deplacementhibergment record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insertSelective(Deplacementhibergment record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    Deplacementhibergment selectByPrimaryKey(Integer iddeplacementhibergement);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKeySelective(Deplacementhibergment record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table deplacementhibergment
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKey(Deplacementhibergment record);
}