package com.web.server.ibatis.dao;

import com.web.server.ibatis.model.Equipement;

public interface EquipementDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int deleteByPrimaryKey(Integer idEquipement);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insert(Equipement record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insertSelective(Equipement record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    Equipement selectByPrimaryKey(Integer idEquipement);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKeySelective(Equipement record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table equipement
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKey(Equipement record);
}