package com.web.server.ibatis.dao;

import com.web.server.ibatis.model.Etudiant;

public interface EtudiantDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int deleteByPrimaryKey(Integer idEtudiant);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insert(Etudiant record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insertSelective(Etudiant record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    Etudiant selectByPrimaryKey(Integer idEtudiant);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKeySelective(Etudiant record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table etudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKey(Etudiant record);
}