package com.web.server.ibatis.dao;

import com.web.server.ibatis.model.Maintenancediveres;

public interface MaintenancediveresDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int deleteByPrimaryKey(Integer idmainetencedivers);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insert(Maintenancediveres record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insertSelective(Maintenancediveres record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    Maintenancediveres selectByPrimaryKey(Integer idmainetencedivers);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKeySelective(Maintenancediveres record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maintenancediveres
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKey(Maintenancediveres record);
}