package com.web.server.ibatis.dao;

import com.web.server.ibatis.model.Manifestationsientifique;

public interface ManifestationsientifiqueDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table manifestationsientifique
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int deleteByPrimaryKey(Integer idmanifastationSientifique);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table manifestationsientifique
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insert(Manifestationsientifique record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table manifestationsientifique
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insertSelective(Manifestationsientifique record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table manifestationsientifique
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    Manifestationsientifique selectByPrimaryKey(Integer idmanifastationSientifique);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table manifestationsientifique
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKeySelective(Manifestationsientifique record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table manifestationsientifique
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKey(Manifestationsientifique record);
}