package com.web.server.ibatis.dao;

import com.web.server.ibatis.model.Missions;

public interface MissionsDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int deleteByPrimaryKey(Integer idmissions);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insert(Missions record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insertSelective(Missions record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    Missions selectByPrimaryKey(Integer idmissions);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKeySelective(Missions record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table missions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKey(Missions record);
}