package com.web.server.ibatis.dao;

import com.web.server.ibatis.model.Renumeration;

public interface RenumerationDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int deleteByPrimaryKey(Integer idrenumaration);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insert(Renumeration record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insertSelective(Renumeration record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    Renumeration selectByPrimaryKey(Integer idrenumaration);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKeySelective(Renumeration record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table renumeration
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKey(Renumeration record);
}