package com.web.server.ibatis.dao;

import com.web.server.ibatis.model.Soustraitance;

public interface SoustraitanceDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int deleteByPrimaryKey(Integer idTraitence);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insert(Soustraitance record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insertSelective(Soustraitance record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    Soustraitance selectByPrimaryKey(Integer idTraitence);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKeySelective(Soustraitance record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table soustraitance
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKey(Soustraitance record);
}