package com.web.server.ibatis.dao;

import com.web.server.ibatis.model.Stage;

public interface StageDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int deleteByPrimaryKey(Integer idStage);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insert(Stage record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    void insertSelective(Stage record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    Stage selectByPrimaryKey(Integer idStage);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKeySelective(Stage record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table stage
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    int updateByPrimaryKey(Stage record);
}