package com.web.server.ibatis.model;

public class Administrateur {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column administrateur.id_admin
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
	

    private Integer id_admin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column administrateur.login
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    private String login;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column administrateur.password
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column administrateur.nom
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    private String nom;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column administrateur.prenom
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    private String prenom;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column administrateur.id_admin
     *
     * @return the value of administrateur.id_admin
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    public Integer getId_admin() {
        return id_admin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column administrateur.id_admin
     *
     * @param id_admin the value for administrateur.id_admin
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    public void setId_admin(Integer id_admin) {
        this.id_admin = id_admin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column administrateur.login
     *
     * @return the value of administrateur.login
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column administrateur.login
     *
     * @param login the value for administrateur.login
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column administrateur.password
     *
     * @return the value of administrateur.password
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column administrateur.password
     *
     * @param password the value for administrateur.password
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column administrateur.nom
     *
     * @return the value of administrateur.nom
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    public String getNom() {
        return nom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column administrateur.nom
     *
     * @param nom the value for administrateur.nom
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    public void setNom(String nom) {
        this.nom = nom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column administrateur.prenom
     *
     * @return the value of administrateur.prenom
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    public String getPrenom() {
        return prenom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column administrateur.prenom
     *
     * @param prenom the value for administrateur.prenom
     *
     * @ibatorgenerated Tue Jul 09 18:42:29 CEST 2013
     */
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
}