package com.web.server.ibatis.model;

public class Demande {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column demande.iddemande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	private Integer iddemande;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column demande.idetudiant
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	private Integer idetudiant;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column demande.depensesnecessaires
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	private Double depensesnecessaires;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column demande.mentant
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	private Double mentant;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column demande.SujetSatge_OfficeMultifiscal
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	private String sujetSatge_OfficeMultifiscal;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column demande.lieu
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	private String lieu;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column demande.nomaboratoire
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	private String nomaboratoire;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column demande.dateDebut
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	private String dateDebut;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column demande.dateFin
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	private String dateFin;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column demande.etatDemande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	private String etatDemande;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column demande.accepte
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	private String accepte;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column demande.iddemande
	 * @return  the value of demande.iddemande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public Integer getIddemande() {
		return iddemande;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column demande.iddemande
	 * @param iddemande  the value for demande.iddemande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void setIddemande(Integer iddemande) {
		this.iddemande = iddemande;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column demande.idetudiant
	 * @return  the value of demande.idetudiant
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public Integer getIdetudiant() {
		return idetudiant;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column demande.idetudiant
	 * @param idetudiant  the value for demande.idetudiant
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void setIdetudiant(Integer idetudiant) {
		this.idetudiant = idetudiant;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column demande.depensesnecessaires
	 * @return  the value of demande.depensesnecessaires
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public Double getDepensesnecessaires() {
		return depensesnecessaires;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column demande.depensesnecessaires
	 * @param depensesnecessaires  the value for demande.depensesnecessaires
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void setDepensesnecessaires(Double depensesnecessaires) {
		this.depensesnecessaires = depensesnecessaires;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column demande.mentant
	 * @return  the value of demande.mentant
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public Double getMentant() {
		return mentant;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column demande.mentant
	 * @param mentant  the value for demande.mentant
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void setMentant(Double mentant) {
		this.mentant = mentant;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column demande.SujetSatge_OfficeMultifiscal
	 * @return  the value of demande.SujetSatge_OfficeMultifiscal
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public String getSujetSatge_OfficeMultifiscal() {
		return sujetSatge_OfficeMultifiscal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column demande.SujetSatge_OfficeMultifiscal
	 * @param sujetSatge_OfficeMultifiscal  the value for demande.SujetSatge_OfficeMultifiscal
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void setSujetSatge_OfficeMultifiscal(
			String sujetSatge_OfficeMultifiscal) {
		this.sujetSatge_OfficeMultifiscal = sujetSatge_OfficeMultifiscal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column demande.lieu
	 * @return  the value of demande.lieu
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public String getLieu() {
		return lieu;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column demande.lieu
	 * @param lieu  the value for demande.lieu
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column demande.nomaboratoire
	 * @return  the value of demande.nomaboratoire
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public String getNomaboratoire() {
		return nomaboratoire;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column demande.nomaboratoire
	 * @param nomaboratoire  the value for demande.nomaboratoire
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void setNomaboratoire(String nomaboratoire) {
		this.nomaboratoire = nomaboratoire;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column demande.dateDebut
	 * @return  the value of demande.dateDebut
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public String getDateDebut() {
		return dateDebut;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column demande.dateDebut
	 * @param dateDebut  the value for demande.dateDebut
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void setDateDebut(String dateDebut) {
		this.dateDebut = dateDebut;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column demande.dateFin
	 * @return  the value of demande.dateFin
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public String getDateFin() {
		return dateFin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column demande.dateFin
	 * @param dateFin  the value for demande.dateFin
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void setDateFin(String dateFin) {
		this.dateFin = dateFin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column demande.etatDemande
	 * @return  the value of demande.etatDemande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public String getEtatDemande() {
		return etatDemande;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column demande.etatDemande
	 * @param etatDemande  the value for demande.etatDemande
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void setEtatDemande(String etatDemande) {
		this.etatDemande = etatDemande;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column demande.accepte
	 * @return  the value of demande.accepte
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public String getAccepte() {
		return accepte;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column demande.accepte
	 * @param accepte  the value for demande.accepte
	 * @ibatorgenerated  Tue Jul 09 23:48:58 CEST 2013
	 */
	public void setAccepte(String accepte) {
		this.accepte = accepte;
	}
}