package com.web.server.ibatis.model;

public class Etudiant {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column etudiant.IdEtudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Integer idEtudiant;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column etudiant.Nom
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private String nom;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column etudiant.Prenom
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private String prenom;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column etudiant.Mobile
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private String mobile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column etudiant.Email
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column etudiant.Cin
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private String cin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column etudiant.Ville
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private String ville;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column etudiant.Login
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private String login;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column etudiant.password
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column etudiant.nationalite
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private String nationalite;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column etudiant.spacialite
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private String spacialite;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column etudiant.IdEtudiant
     *
     * @return the value of etudiant.IdEtudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Integer getIdEtudiant() {
        return idEtudiant;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column etudiant.IdEtudiant
     *
     * @param idEtudiant the value for etudiant.IdEtudiant
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setIdEtudiant(Integer idEtudiant) {
        this.idEtudiant = idEtudiant;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column etudiant.Nom
     *
     * @return the value of etudiant.Nom
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public String getNom() {
        return nom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column etudiant.Nom
     *
     * @param nom the value for etudiant.Nom
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setNom(String nom) {
        this.nom = nom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column etudiant.Prenom
     *
     * @return the value of etudiant.Prenom
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public String getPrenom() {
        return prenom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column etudiant.Prenom
     *
     * @param prenom the value for etudiant.Prenom
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column etudiant.Mobile
     *
     * @return the value of etudiant.Mobile
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column etudiant.Mobile
     *
     * @param mobile the value for etudiant.Mobile
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column etudiant.Email
     *
     * @return the value of etudiant.Email
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column etudiant.Email
     *
     * @param email the value for etudiant.Email
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column etudiant.Cin
     *
     * @return the value of etudiant.Cin
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public String getCin() {
        return cin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column etudiant.Cin
     *
     * @param cin the value for etudiant.Cin
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setCin(String cin) {
        this.cin = cin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column etudiant.Ville
     *
     * @return the value of etudiant.Ville
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public String getVille() {
        return ville;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column etudiant.Ville
     *
     * @param ville the value for etudiant.Ville
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setVille(String ville) {
        this.ville = ville;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column etudiant.Login
     *
     * @return the value of etudiant.Login
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column etudiant.Login
     *
     * @param login the value for etudiant.Login
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column etudiant.password
     *
     * @return the value of etudiant.password
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column etudiant.password
     *
     * @param password the value for etudiant.password
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column etudiant.nationalite
     *
     * @return the value of etudiant.nationalite
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public String getNationalite() {
        return nationalite;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column etudiant.nationalite
     *
     * @param nationalite the value for etudiant.nationalite
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setNationalite(String nationalite) {
        this.nationalite = nationalite;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column etudiant.spacialite
     *
     * @return the value of etudiant.spacialite
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public String getSpacialite() {
        return spacialite;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column etudiant.spacialite
     *
     * @param spacialite the value for etudiant.spacialite
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setSpacialite(String spacialite) {
        this.spacialite = spacialite;
    }
}