package com.web.server.ibatis.model;

public class Maintenancediveres {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column maintenancediveres.idmainetencedivers
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Integer idmainetencedivers;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column maintenancediveres.reliquat2012
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double reliquat2012;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column maintenancediveres.reliquat2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double reliquat2013;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column maintenancediveres.creditaloue
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double creditaloue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column maintenancediveres.depense2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double depense2013;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column maintenancediveres.idmainetencedivers
     *
     * @return the value of maintenancediveres.idmainetencedivers
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Integer getIdmainetencedivers() {
        return idmainetencedivers;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column maintenancediveres.idmainetencedivers
     *
     * @param idmainetencedivers the value for maintenancediveres.idmainetencedivers
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setIdmainetencedivers(Integer idmainetencedivers) {
        this.idmainetencedivers = idmainetencedivers;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column maintenancediveres.reliquat2012
     *
     * @return the value of maintenancediveres.reliquat2012
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getReliquat2012() {
        return reliquat2012;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column maintenancediveres.reliquat2012
     *
     * @param reliquat2012 the value for maintenancediveres.reliquat2012
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setReliquat2012(Double reliquat2012) {
        this.reliquat2012 = reliquat2012;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column maintenancediveres.reliquat2013
     *
     * @return the value of maintenancediveres.reliquat2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getReliquat2013() {
        return reliquat2013;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column maintenancediveres.reliquat2013
     *
     * @param reliquat2013 the value for maintenancediveres.reliquat2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setReliquat2013(Double reliquat2013) {
        this.reliquat2013 = reliquat2013;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column maintenancediveres.creditaloue
     *
     * @return the value of maintenancediveres.creditaloue
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getCreditaloue() {
        return creditaloue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column maintenancediveres.creditaloue
     *
     * @param creditaloue the value for maintenancediveres.creditaloue
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setCreditaloue(Double creditaloue) {
        this.creditaloue = creditaloue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column maintenancediveres.depense2013
     *
     * @return the value of maintenancediveres.depense2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getDepense2013() {
        return depense2013;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column maintenancediveres.depense2013
     *
     * @param depense2013 the value for maintenancediveres.depense2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setDepense2013(Double depense2013) {
        this.depense2013 = depense2013;
    }
}