package com.web.server.ibatis.model;

public class Missions {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column missions.idmissions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Integer idmissions;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column missions.reliquat2012
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double reliquat2012;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column missions.reliquat2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double reliquat2013;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column missions.creditaloue
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double creditaloue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column missions.depense2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double depense2013;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column missions.idmissions
     *
     * @return the value of missions.idmissions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Integer getIdmissions() {
        return idmissions;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column missions.idmissions
     *
     * @param idmissions the value for missions.idmissions
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setIdmissions(Integer idmissions) {
        this.idmissions = idmissions;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column missions.reliquat2012
     *
     * @return the value of missions.reliquat2012
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getReliquat2012() {
        return reliquat2012;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column missions.reliquat2012
     *
     * @param reliquat2012 the value for missions.reliquat2012
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setReliquat2012(Double reliquat2012) {
        this.reliquat2012 = reliquat2012;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column missions.reliquat2013
     *
     * @return the value of missions.reliquat2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getReliquat2013() {
        return reliquat2013;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column missions.reliquat2013
     *
     * @param reliquat2013 the value for missions.reliquat2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setReliquat2013(Double reliquat2013) {
        this.reliquat2013 = reliquat2013;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column missions.creditaloue
     *
     * @return the value of missions.creditaloue
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getCreditaloue() {
        return creditaloue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column missions.creditaloue
     *
     * @param creditaloue the value for missions.creditaloue
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setCreditaloue(Double creditaloue) {
        this.creditaloue = creditaloue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column missions.depense2013
     *
     * @return the value of missions.depense2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getDepense2013() {
        return depense2013;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column missions.depense2013
     *
     * @param depense2013 the value for missions.depense2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setDepense2013(Double depense2013) {
        this.depense2013 = depense2013;
    }
}