package com.web.server.ibatis.model;

public class Soustraitance {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column soustraitance.idTraitence
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Integer idTraitence;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column soustraitance.reliquat2012
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double reliquat2012;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column soustraitance.reliquat2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double reliquat2013;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column soustraitance.creditaloue
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double creditaloue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column soustraitance.depense2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    private Double depense2013;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column soustraitance.idTraitence
     *
     * @return the value of soustraitance.idTraitence
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Integer getIdTraitence() {
        return idTraitence;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column soustraitance.idTraitence
     *
     * @param idTraitence the value for soustraitance.idTraitence
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setIdTraitence(Integer idTraitence) {
        this.idTraitence = idTraitence;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column soustraitance.reliquat2012
     *
     * @return the value of soustraitance.reliquat2012
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getReliquat2012() {
        return reliquat2012;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column soustraitance.reliquat2012
     *
     * @param reliquat2012 the value for soustraitance.reliquat2012
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setReliquat2012(Double reliquat2012) {
        this.reliquat2012 = reliquat2012;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column soustraitance.reliquat2013
     *
     * @return the value of soustraitance.reliquat2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getReliquat2013() {
        return reliquat2013;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column soustraitance.reliquat2013
     *
     * @param reliquat2013 the value for soustraitance.reliquat2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setReliquat2013(Double reliquat2013) {
        this.reliquat2013 = reliquat2013;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column soustraitance.creditaloue
     *
     * @return the value of soustraitance.creditaloue
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getCreditaloue() {
        return creditaloue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column soustraitance.creditaloue
     *
     * @param creditaloue the value for soustraitance.creditaloue
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setCreditaloue(Double creditaloue) {
        this.creditaloue = creditaloue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column soustraitance.depense2013
     *
     * @return the value of soustraitance.depense2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public Double getDepense2013() {
        return depense2013;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column soustraitance.depense2013
     *
     * @param depense2013 the value for soustraitance.depense2013
     *
     * @ibatorgenerated Thu Jul 04 11:24:21 CEST 2013
     */
    public void setDepense2013(Double depense2013) {
        this.depense2013 = depense2013;
    }
}